name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/login-backend ./backend
        docker push ${{ secrets.DOCKER_USERNAME }}/login-backend

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/login-frontend -f ./frontend/Dockerfile ./frontend || true